repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint (python)
        entry: python -m pylint
        language: system
        types: [python]
        args: ["--rcfile=.pylintrc"]
